-- BORRADOR PARA FUTURA CONEXIÓN A SUPABASE
-- Esta V5 aún funciona en localStorage.

create table if not exists pr_users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  pin_hash text not null,
  avatar text not null default '🙂',
  streak integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists pr_scores (
  id bigint generated by default as identity primary key,
  username text not null references pr_users(username),
  avatar text not null default '🙂',
  game text not null,
  points integer not null default 0,
  detail text,
  result text,
  created_at timestamptz not null default now()
);

create table if not exists pr_rooms (
  code text primary key,
  game text not null,
  host_username text not null references pr_users(username),
  guest_username text references pr_users(username),
  status text not null default 'waiting',
  created_at timestamptz not null default now()
);

create table if not exists pr_achievements (
  username text not null references pr_users(username),
  achievement_id text not null,
  created_at timestamptz not null default now(),
  primary key(username, achievement_id)
);


-- Campos recomendados para V6 bilingüe/avatar:
-- players.avatar_code: código del avatar elegido por el jugador.
-- players.language: 'es' o 'va'. Solo afecta a la interfaz del jugador.
-- La CPU no debe estar en la tabla de jugadores seleccionables.
-- Avatar reservado de CPU: 🤖.
