-- Esquema inicial orientativo para cuando conectemos Supabase.
-- En la V2 de prueba actual, la app usa localStorage para validar interfaz y flujo.

create table if not exists public.jds_users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  pin_hash text not null,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.jds_games (
  id text primary key,
  name text not null,
  max_players integer not null default 1,
  is_active boolean not null default true
);

insert into public.jds_games (id, name, max_players, is_active)
values ('pong', 'Pong', 2, true)
on conflict (id) do nothing;

create table if not exists public.jds_scores (
  id bigint generated by default as identity primary key,
  game_id text not null references public.jds_games(id),
  user_id uuid not null references public.jds_users(id),
  points integer not null default 0,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.jds_rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  game_id text not null references public.jds_games(id),
  host_user_id uuid not null references public.jds_users(id),
  guest_user_id uuid references public.jds_users(id),
  status text not null default 'waiting',
  created_at timestamptz not null default now()
);

-- Nota de seguridad para fase real:
-- 1) Activar RLS.
-- 2) No guardar PIN en claro: usar hash desde función SQL o backend.
-- 3) El filtro de palabras malsonantes del frontend es solo una primera barrera; debe repetirse en base/backend.
